// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClei1_mNeBnZMIN-Zn4qcWNvWyxNwEASc',
    appId: '1:771301020939:web:742c307c60c29a8e263e0e',
    messagingSenderId: '771301020939',
    projectId: 'facebook-acbd4',
    authDomain: 'facebook-acbd4.firebaseapp.com',
    storageBucket: 'facebook-acbd4.firebasestorage.app',
    measurementId: 'G-ZBZS0JRT8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftJHbmlqrfh7D1XwqvksEFu5i020OE1M',
    appId: '1:771301020939:android:11c1eb56c2db5ecc263e0e',
    messagingSenderId: '771301020939',
    projectId: 'facebook-acbd4',
    storageBucket: 'facebook-acbd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsP43_Ruas2_X1-JM5KOg0Ulyr7cBndYE',
    appId: '1:771301020939:ios:fe3fa65067c8498e263e0e',
    messagingSenderId: '771301020939',
    projectId: 'facebook-acbd4',
    storageBucket: 'facebook-acbd4.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsP43_Ruas2_X1-JM5KOg0Ulyr7cBndYE',
    appId: '1:771301020939:ios:fe3fa65067c8498e263e0e',
    messagingSenderId: '771301020939',
    projectId: 'facebook-acbd4',
    storageBucket: 'facebook-acbd4.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClei1_mNeBnZMIN-Zn4qcWNvWyxNwEASc',
    appId: '1:771301020939:web:771aa6976a4f4ab0263e0e',
    messagingSenderId: '771301020939',
    projectId: 'facebook-acbd4',
    authDomain: 'facebook-acbd4.firebaseapp.com',
    storageBucket: 'facebook-acbd4.firebasestorage.app',
    measurementId: 'G-SH2M9ZZ80Q',
  );

}